# Generated by Django 5.2.7 on 2025-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='meaning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='pronounciation',
            field=models.TextField(blank=True),
        ),
    ]
