# Generated by Django 5.2.7 on 2025-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_response_meaning_response_pronounciation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='pronounciation',
        ),
        migrations.AddField(
            model_name='response',
            name='pronunciation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='response',
            name='meaning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
